"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import axios from "axios";
import { CalendarDays, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { EmptyState } from "@/components/ui/empty-state";
import { useToast } from "@/components/ui/toast";
import { addDays, daysBetween, formatDisplayDate, formatDisplayDateRange } from "@/lib/travel/engine/dates";
import { normalizeDayServices, type DayServiceItem, type ScenarioResultLine } from "@/lib/travel/contracts";
import DateField from "@/components/travel/DateField";
import ServicePickerDialog, { type ServicePickerTab } from "../ServicePickerDialog";
import { apiError, money } from "../utils";
import type { RateView, ServiceProductView, VehicleTypeView } from "../types";
import type { DetailContext } from "./RequestDetail";

interface DayDraft {
  dayOffset: number;
  date: string;
  narrative: string;
  overnightCity: string;
  services: DayServiceItem[];
}

/** date → overnight city from the first scenario's stays ([checkIn, checkOut)). */
function deriveCityByDate(ctx: DetailContext): Record<string, string> {
  const map: Record<string, string> = {};
  const stays = ctx.version.scenarios[0]?.stays ?? [];
  for (const stay of stays) {
    if (!stay.city) continue;
    for (let date = stay.checkIn; date < stay.checkOut; date = addDays(date, 1)) {
      map[date] = stay.city;
    }
  }
  return map;
}

export default function ItineraryTab({ ctx }: { ctx: DetailContext }) {
  const { toast } = useToast();
  const { version } = ctx;
  const [days, setDays] = useState<DayDraft[]>([]);
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [products, setProducts] = useState<ServiceProductView[] | null>(null);
  const [vehicles, setVehicles] = useState<VehicleTypeView[]>([]);
  // Which day's picker is open and on which tab (per-column add buttons).
  const [picker, setPicker] = useState<{ day: number; tab: ServicePickerTab } | null>(null);
  // Auto-generation runs once per version id — the ref guards against React
  // StrictMode double-invoking the effect before the save lands.
  const autoGeneratedFor = useRef<string | null>(null);
  // Cities this component auto-filled, keyed by dayOffset — the sync never
  // overwrites a value the user typed over a derived one.
  const derivedCities = useRef<Record<number, string>>({});

  const hasStays = version.scenarios.some((sc) => sc.stays.length > 0);

  useEffect(() => {
    const loaded: DayDraft[] = version.itineraryDays.map((d) => ({
      dayOffset: d.dayOffset,
      date: d.date,
      narrative: d.narrative ?? "",
      overnightCity: d.overnightCity ?? "",
      services: normalizeDayServices(d.services),
    }));
    // Pre-fill overnight cities from stays (blank fields only — typed values
    // are never touched). Deterministic from the stays, so not marked dirty.
    derivedCities.current = {};
    let next = loaded;
    if (version.scenarios.some((sc) => sc.stays.length > 0)) {
      const cityByDate = deriveCityByDate(ctx);
      next = loaded.map((d, i) => {
        const derived = cityByDate[d.date] ?? "";
        if (derived && d.overnightCity === "") {
          derivedCities.current[i] = derived;
          return { ...d, overnightCity: derived };
        }
        return d;
      });
    }
    setDays(next);
    setDirty(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [version.id, version.itineraryDays]);

  // The catalog also drives the read-only Tours/Tickets/Services grouping
  // (categoryOf), so load it unconditionally — same reasoning as the vehicle
  // names below.
  useEffect(() => {
    if (products !== null) return;
    axios
      .get("/api/travel/catalog/services")
      .then((res) => setProducts(res.data))
      .catch((err) => toast(apiError(err, "Failed to load service catalog"), "error"));
  }, [products, toast]);

  // Vehicle names also render on read-only chips, so load them unconditionally.
  useEffect(() => {
    axios
      .get("/api/travel/catalog/vehicles")
      .then((res) => setVehicles(res.data))
      .catch(() => null);
  }, []);

  // FX map for the picker's indicative-rate hints (AMD per 1 unit, as of today).
  const [fxRates, setFxRates] = useState<Record<string, string> | null>(null);
  useEffect(() => {
    const today = new Date().toISOString().slice(0, 10);
    axios
      .get(`/api/travel/fx?asOf=${today}`)
      .then((res) => setFxRates(res.data?.rates ?? null))
      .catch(() => null);
  }, []);

  // Per-line net costs from the shared quote preview (v0.11.0). Day-linked
  // lines are shared across scenarios, so the first scenario's lines suffice.
  // Absent for redacted advisors and pre-v0.11.0 snapshots — costs then hide.
  const canSeeCosts = ctx.isAdmin || ctx.role === "VALIDATOR" || ctx.isOwner;
  const costByKey = useMemo(() => {
    const map = new Map<string, ScenarioResultLine>();
    if (!canSeeCosts) return map;
    const firstScenarioId = version.scenarios[0]?.id;
    const result = firstScenarioId ? ctx.quoteResults?.get(firstScenarioId) : null;
    for (const line of result?.lines ?? []) {
      if (line.serviceProductId && line.date) {
        map.set(`${line.serviceProductId}|${line.date}|${line.vehicleTypeId ?? ""}`, line);
      }
    }
    return map;
  }, [canSeeCosts, ctx.quoteResults, version.scenarios]);

  const vehicleName = (id: string | null | undefined) =>
    id ? vehicles.find((v) => v.id === id)?.name ?? null : null;

  /** Catalog category for a day service; label-only services fall to "OTHER". */
  const categoryOf = (s: DayServiceItem): string =>
    s.serviceProductId ? products?.find((p) => p.id === s.serviceProductId)?.category ?? "OTHER" : "OTHER";

  const serviceCost = (s: DayServiceItem, date: string): ScenarioResultLine | undefined =>
    s.serviceProductId ? costByKey.get(`${s.serviceProductId}|${date}|${s.vehicleTypeId ?? ""}`) : undefined;

  function setServiceQuantity(dayIdx: number, svcIdx: number, delta: number) {
    const services = days[dayIdx].services.map((s, j) =>
      j === svcIdx ? { ...s, quantity: Math.max(1, (s.quantity ?? 1) + delta) } : s,
    );
    update(dayIdx, { services });
  }

  /**
   * Indicative catalog rate for the picker: the highest-priority row covering
   * the picked day's date (the same band resolve.ts would price from), vehicle
   * rows preferred when a vehicle is chosen. Indicative only — ambiguity and
   * quote-on-request simply yield no hint.
   */
  function indicativeRate(date: string | undefined, p: ServiceProductView, vehicleTypeId?: string): RateView | null {
    if (!date) return null;
    const covers = (r: RateView) => (r.validFrom ?? "") <= date && date < (r.validTo ?? "￿");
    let pool = p.rates.filter((r) => r.amount !== null && !r.quoteOnRequest);
    if (vehicleTypeId) {
      const vehicleRows = pool.filter((r) => r.vehicleTypeId === vehicleTypeId);
      pool = vehicleRows.some(covers) ? vehicleRows : pool.filter((r) => r.vehicleTypeId === null);
    }
    const covering = pool.filter(covers);
    if (covering.length === 0) return null;
    const top = Math.max(...covering.map((r) => r.priority));
    return covering.filter((r) => r.priority === top)[0] ?? null;
  }

  /** "≈ 12000 AMD · 32.88 USD" hint for a catalog rate row; null without FX. */
  function rateHint(r: RateView | null): string | null {
    if (!r?.amount) return null;
    const parts = [money(r.amount, r.currency)];
    if (fxRates) {
      const perAmd = Number(fxRates[r.currency] ?? (r.currency === "AMD" ? "1" : "0"));
      const quoteRate = Number(fxRates[ctx.resultCurrency] ?? (ctx.resultCurrency === "AMD" ? "1" : "0"));
      if (perAmd > 0) {
        const amd = Number(r.amount) * perAmd;
        if (r.currency !== "AMD") parts.push(`≈ ${money(amd.toFixed(2), "AMD")}`);
        if (quoteRate > 0 && ctx.resultCurrency !== "AMD" && ctx.resultCurrency !== r.currency) {
          parts.push(`≈ ${money((amd / quoteRate).toFixed(2), ctx.resultCurrency)}`);
        }
      }
    }
    return parts.join(" · ");
  }

  function applyCitySync(source: DayDraft[], markDirty: boolean) {
    const cityByDate = deriveCityByDate(ctx);
    let changed = false;
    const next = source.map((d, i) => {
      const derived = cityByDate[d.date] ?? "";
      const previous = derivedCities.current[i];
      // Fill only blanks and values WE derived earlier; typed cities stay.
      if (derived && (d.overnightCity === "" || d.overnightCity === previous)) {
        if (d.overnightCity !== derived) changed = true;
        derivedCities.current[i] = derived;
        return { ...d, overnightCity: derived };
      }
      return d;
    });
    if (changed) {
      setDays(next);
      if (markDirty) setDirty(true);
    }
    return changed;
  }

  function update(idx: number, patch: Partial<DayDraft>) {
    setDays((prev) => prev.map((d, i) => (i === idx ? { ...d, ...patch } : d)));
    setDirty(true);
  }

  function rederiveDates(list: DayDraft[]): DayDraft[] {
    // Dates are derived from the request start date so offset and date never diverge.
    return list.map((d, i) => ({ ...d, dayOffset: i, date: addDays(ctx.detail.startDate, i) }));
  }

  /** Pure builder: one blank day per travel date, cities pre-filled from stays. */
  function buildGeneratedDays(): DayDraft[] {
    const count = daysBetween(ctx.detail.startDate, ctx.detail.endDate);
    const generated: DayDraft[] = Array.from({ length: count }, (_, i) => ({
      dayOffset: i,
      date: addDays(ctx.detail.startDate, i),
      narrative: "",
      overnightCity: "",
      services: [],
    }));
    derivedCities.current = {};
    if (!hasStays) return generated;
    const cityMap = deriveCityByDate(ctx);
    return generated.map((d, i) => {
      const derived = cityMap[d.date] ?? "";
      if (derived) {
        derivedCities.current[i] = derived;
        return { ...d, overnightCity: derived };
      }
      return d;
    });
  }

  function generateFromTravelDates() {
    setDays(buildGeneratedDays());
    setDirty(true);
  }

  function addDay() {
    setDays(
      rederiveDates([
        ...days,
        { dayOffset: days.length, date: addDays(ctx.detail.startDate, days.length), narrative: "", overnightCity: "", services: [] },
      ]),
    );
    setDirty(true);
  }

  function removeDay(idx: number) {
    setDays(rederiveDates(days.filter((_, i) => i !== idx)));
    setDirty(true);
  }

  function addService(idx: number, item: DayServiceItem) {
    const day = days[idx];
    const patch: Partial<DayDraft> = { services: [...day.services, item] };
    // Narrative auto-fill is tracked by string equality only: fill from the
    // added tour's details when the narrative is blank or still verbatim-equal
    // to a tour added earlier — a narrative the user typed over never moves.
    if (item.details && categoryOf(item) === "TRANSPORTATION") {
      const untouched =
        day.narrative === "" ||
        day.services.some((s) => categoryOf(s) === "TRANSPORTATION" && s.details != null && s.details === day.narrative);
      if (untouched) patch.narrative = item.details;
    }
    update(idx, patch);
  }

  function removeService(dayIdx: number, svcIdx: number) {
    const day = days[dayIdx];
    const removed = day.services[svcIdx];
    const patch: Partial<DayDraft> = { services: day.services.filter((_, i) => i !== svcIdx) };
    // Clear the narrative only while it still holds the removed tour's
    // auto-filled details verbatim; user-edited text survives the removal.
    if (removed?.details && categoryOf(removed) === "TRANSPORTATION" && day.narrative === removed.details) {
      patch.narrative = "";
    }
    update(dayIdx, patch);
  }

  /** Persists an explicit day list — callers pass the list so an auto-save right after generation never depends on setState timing. */
  async function saveDays(list: DayDraft[], successMessage: string) {
    setSaving(true);
    try {
      await axios.put(`/api/travel/versions/${version.id}/content`, {
        expectedRevision: ctx.detail.revision,
        itineraryDays: list.map((d) => ({
          dayOffset: d.dayOffset,
          date: d.date,
          narrative: d.narrative || null,
          overnightCity: d.overnightCity || null,
          services: d.services.map((s) => ({
            serviceProductId: s.serviceProductId,
            label: s.label,
            details: s.details ?? null,
            vehicleTypeId: s.vehicleTypeId ?? null,
            quantity: s.quantity ?? null,
          })),
        })),
      });
      toast(successMessage, "success");
      setDirty(false);
      ctx.refresh();
    } catch (err: any) {
      if (err?.response?.status === 409) {
        toast("This request was edited elsewhere — refreshed the latest data. Review and save again.", "error");
        ctx.refresh();
      } else {
        toast(apiError(err, "Failed to save itinerary"), "error");
      }
    } finally {
      setSaving(false);
    }
  }

  function handleSave() {
    return saveDays(days, "Itinerary saved");
  }

  // A fresh version starts with no days: generate them from the travel dates
  // and save immediately, so the advisor lands on a ready day grid instead of
  // an empty placeholder. Editable versions only; once per version id.
  useEffect(() => {
    if (!ctx.canEditVersion) return;
    if (version.itineraryDays.length > 0) return;
    if (autoGeneratedFor.current === version.id) return;
    autoGeneratedFor.current = version.id;
    const generated = buildGeneratedDays();
    setDays(generated);
    void saveDays(generated, `Generated ${generated.length} days from travel dates`);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ctx.canEditVersion, version.id, version.itineraryDays.length]);

  const cityByDate = hasStays ? deriveCityByDate(ctx) : {};

  return (
    <div>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-base font-semibold tracking-tight">Itinerary</h2>
          <p className="text-[13px] text-muted-foreground">
            Day-by-day plan for this version.{ctx.canEditVersion ? "" : " Read-only for this version status."}
          </p>
        </div>
        {ctx.canEditVersion && (
          <div className="flex gap-2">
            {hasStays && (
              <Button variant="outline" size="sm" onClick={() => applyCitySync(days, true)}>
                Sync cities from stays
              </Button>
            )}
            <Button variant="outline" size="sm" onClick={addDay}>
              Add day
            </Button>
            <Button size="sm" onClick={handleSave} disabled={!dirty || saving}>
              {saving ? "Saving..." : "Save itinerary"}
            </Button>
          </div>
        )}
      </div>
      <div>
        {days.length === 0 &&
          (ctx.canEditVersion ? (
            <EmptyState
              icon={CalendarDays}
              title="No itinerary days yet"
              description={`Generate one day per travel date (${formatDisplayDateRange(ctx.detail.startDate, ctx.detail.endDate)}) or add days manually.`}
              action={<Button onClick={generateFromTravelDates}>Generate days from travel dates</Button>}
            />
          ) : (
            <EmptyState icon={CalendarDays} title="No itinerary days yet" />
          ))}
        {/* Timeline: the day number rides a left rail; day cards are the only
            containment layer (no card-in-card). */}
        <div className="space-y-4">
          {days.map((d, i) => {
            const rail = (
              <div className="flex w-8 shrink-0 flex-col items-center">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border bg-card text-xs font-semibold text-foreground">
                  {d.dayOffset + 1}
                </span>
                {i < days.length - 1 && <span className="mt-1 w-px flex-1 bg-border" />}
              </div>
            );
            // Tours and Tickets & degustations get their own panels (edit mode:
            // with quantity steppers and net costs, v0.11.0); other categories
            // stay as a plain chips row.
            const tours = d.services.map((s, j) => ({ s, j })).filter(({ s }) => categoryOf(s) === "TRANSPORTATION");
            const tickets = d.services.map((s, j) => ({ s, j })).filter(({ s }) => categoryOf(s) === "TICKETS");
            const others = d.services
              .map((s, j) => ({ s, j }))
              .filter(({ s }) => !["TRANSPORTATION", "TICKETS"].includes(categoryOf(s)));

            if (!ctx.canEditVersion) {
              const readGroup = (title: string, items: { s: DayServiceItem; j: number }[]) =>
                items.length === 0 ? null : (
                  <div>
                    <p className="mb-1 text-xs font-medium text-muted-foreground">{title}</p>
                    <div className="flex flex-wrap gap-1">
                      {items.map(({ s, j }) => (
                        <Badge key={j} variant="outline" className="text-xs font-normal text-muted-foreground">
                          {s.label}
                          {(s.quantity ?? 1) > 1 ? ` ×${s.quantity}` : ""}
                          {vehicleName(s.vehicleTypeId) ? ` · ${vehicleName(s.vehicleTypeId)}` : ""}
                        </Badge>
                      ))}
                    </div>
                  </div>
                );
              return (
                <div key={i} className="flex gap-3">
                  {rail}
                  <div className="min-w-0 flex-1 rounded-xl border bg-card p-4 text-sm shadow-[0_1px_2px_rgb(0_0_0/0.04)]">
                    <div className="mb-1 flex items-center gap-3 font-medium">
                      <span className="text-muted-foreground">{formatDisplayDate(d.date)}</span>
                      {d.overnightCity && <span className="text-muted-foreground">· {d.overnightCity}</span>}
                    </div>
                    {d.narrative && <p className="whitespace-pre-wrap">{d.narrative}</p>}
                    {d.services.length > 0 && (
                      <div className="mt-2 grid gap-3 sm:grid-cols-2">
                        {readGroup("Tours", tours)}
                        {readGroup("Tickets & degustations", tickets)}
                        {readGroup("Services", others)}
                      </div>
                    )}
                  </div>
                </div>
              );
            }

            const renderEntry = ({ s, j }: { s: DayServiceItem; j: number }) => {
              const cost = serviceCost(s, d.date);
              return (
                <div key={j} className="flex items-center gap-2 rounded-lg border bg-card px-2 py-1 text-[13px]">
                  <span className="flex-1">
                    {s.label}
                    {vehicleName(s.vehicleTypeId) && (
                      <span className="text-xs text-muted-foreground"> · {vehicleName(s.vehicleTypeId)}</span>
                    )}
                  </span>
                  <span className="flex items-center gap-1">
                    <button
                      type="button"
                      aria-label={`Decrease ${s.label} quantity`}
                      className="h-5 w-5 rounded border bg-card text-xs leading-none transition-colors hover:bg-muted disabled:opacity-40"
                      disabled={(s.quantity ?? 1) <= 1}
                      onClick={() => setServiceQuantity(i, j, -1)}
                    >
                      −
                    </button>
                    <span className="w-5 text-center text-xs [font-variant-numeric:tabular-nums]">{s.quantity ?? 1}</span>
                    <button
                      type="button"
                      aria-label={`Increase ${s.label} quantity`}
                      className="h-5 w-5 rounded border bg-card text-xs leading-none transition-colors hover:bg-muted"
                      onClick={() => setServiceQuantity(i, j, 1)}
                    >
                      +
                    </button>
                  </span>
                  {cost?.amountAmd != null && (
                    <span className="whitespace-nowrap text-xs text-muted-foreground [font-variant-numeric:tabular-nums]">
                      {money(cost.amountAmd, "AMD")}
                      {cost.amountQuote != null && ctx.resultCurrency !== "AMD"
                        ? ` · ${money(cost.amountQuote, ctx.resultCurrency)}`
                        : ""}
                    </span>
                  )}
                  <button
                    type="button"
                    aria-label={`Remove ${s.label}`}
                    className="text-muted-foreground transition-colors hover:text-destructive"
                    onClick={() => removeService(i, j)}
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>
              );
            };
            const panel = (
              title: string,
              items: { s: DayServiceItem; j: number }[],
              tab: ServicePickerTab,
              addLabel: string,
              emptyLabel: string,
            ) => (
              <div className="rounded-lg border border-dashed bg-muted/20 p-2">
                <div className="mb-1 flex items-center justify-between gap-2">
                  <p className="text-xs font-medium text-muted-foreground">{title}</p>
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-6 px-2 text-xs"
                    onClick={() => setPicker({ day: i, tab })}
                  >
                    {addLabel}
                  </Button>
                </div>
                <div className="space-y-1">
                  {items.map(renderEntry)}
                  {items.length === 0 && <p className="py-1 text-xs text-muted-foreground">{emptyLabel}</p>}
                </div>
              </div>
            );
            return (
              <div key={i} className="flex gap-3">
                {rail}
                <div className="min-w-0 flex-1 rounded-xl border bg-card p-4 shadow-[0_1px_2px_rgb(0_0_0/0.04)]">
                  <div className="flex flex-wrap items-center gap-2">
                    <DateField
                      className="w-[150px]"
                      value={d.date}
                      onChange={(iso) => update(i, { date: iso })}
                    />
                    <div className="min-w-[180px] flex-1">
                      <Input
                        placeholder="Overnight city"
                        className="h-8 text-[13px]"
                        value={d.overnightCity}
                        onChange={(e) => update(i, { overnightCity: e.target.value })}
                      />
                      {hasStays && !cityByDate[d.date] && (
                        // Nights span [startDate, endDate): the departure day has no
                        // overnight by definition — hint instead of warning.
                        d.date >= ctx.detail.endDate ? (
                          <p className="mt-1 text-xs text-muted-foreground">Departure day — no overnight needed</p>
                        ) : (
                          <p className="mt-1 text-xs text-amber-600">No stay covers this date</p>
                        )
                      )}
                    </div>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 text-muted-foreground hover:text-destructive"
                      aria-label={`Remove day ${d.dayOffset + 1}`}
                      onClick={() => removeDay(i)}
                    >
                      <X />
                    </Button>
                  </div>
                  <Textarea
                    className="mt-2"
                    rows={2}
                    placeholder="Narrative"
                    value={d.narrative}
                    onChange={(e) => update(i, { narrative: e.target.value })}
                  />
                  <div className="mt-3 grid gap-3 sm:grid-cols-2">
                    {panel("Tours", tours, "tours", "+ Add tour", "No tours yet")}
                    {panel("Tickets & degustations", tickets, "tickets", "+ Add ticket", "No tickets yet")}
                  </div>
                  <div className="mt-2 flex flex-wrap content-start items-start gap-1">
                    {others.map(({ s, j }) => (
                      <Badge key={j} variant="outline" className="flex items-center gap-1">
                        {s.label}
                        {(s.quantity ?? 1) > 1 ? ` ×${s.quantity}` : ""}
                        {vehicleName(s.vehicleTypeId) ? ` · ${vehicleName(s.vehicleTypeId)}` : ""}
                        <button
                          type="button"
                          aria-label={`Remove ${s.label}`}
                          className="text-muted-foreground transition-colors hover:text-destructive"
                          onClick={() => removeService(i, j)}
                        >
                          <X className="h-3 w-3" />
                        </button>
                      </Badge>
                    ))}
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-6 px-2 text-xs"
                      onClick={() => setPicker({ day: i, tab: "services" })}
                    >
                      + Add service
                    </Button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
      <ServicePickerDialog
        open={picker !== null}
        onOpenChange={(open) => !open && setPicker(null)}
        initialTab={picker?.tab ?? "tours"}
        title={`Add service${picker !== null ? ` — Day ${days[picker.day]?.dayOffset + 1}` : ""}`}
        description="Pick a catalog service (priced automatically from its rate on this date) or add a custom label."
        products={products}
        vehicles={vehicles}
        rateHint={(p, vehicleTypeId) =>
          rateHint(indicativeRate(picker !== null ? days[picker.day]?.date : undefined, p, vehicleTypeId))
        }
        onPick={(item) => {
          if (picker === null) return;
          addService(picker.day, item);
          setPicker(null);
        }}
      />
    </div>
  );
}
