"use client";

import { useEffect, useRef, useState } from "react";
import axios from "axios";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/components/ui/toast";
import { addDays, daysBetween } from "@/lib/travel/engine/dates";
import { normalizeDayServices, type DayServiceItem } from "@/lib/travel/contracts";
import { apiError, basisLabel, parseJson } from "../utils";
import type { ServiceProductView, VehicleTypeView } from "../types";
import type { DetailContext } from "./RequestDetail";

/**
 * Only per-vehicle bases take a fleet vehicle. Per-seat group tours are
 * TRANSPORTATION too but sell seats on a fixed departure — attaching a vehicle
 * to them mislabels the line ("· Sedan" on a shared tour).
 */
function needsVehicle(p: ServiceProductView): boolean {
  return p.basis === "VEHICLE_TRIP" || p.basis === "VEHICLE_DAY";
}

const ISO_WEEKDAY_SHORT = ["", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

/** "Wed · Fri · Sun" from a JSON ISO-weekday array ("[3,5,7]"), else null. */
function weekdaysLabel(raw: string | null): string | null {
  const days = parseJson<number[]>(raw, []);
  if (days.length === 0) return null;
  return days.map((d) => ISO_WEEKDAY_SHORT[d] ?? String(d)).join(" · ");
}

interface DayDraft {
  dayOffset: number;
  date: string;
  narrative: string;
  overnightCity: string;
  services: DayServiceItem[];
}

/** date → overnight city from the first scenario's stays ([checkIn, checkOut)). */
function deriveCityByDate(ctx: DetailContext): Record<string, string> {
  const map: Record<string, string> = {};
  const stays = ctx.version.scenarios[0]?.stays ?? [];
  for (const stay of stays) {
    if (!stay.city) continue;
    for (let date = stay.checkIn; date < stay.checkOut; date = addDays(date, 1)) {
      map[date] = stay.city;
    }
  }
  return map;
}

export default function ItineraryTab({ ctx }: { ctx: DetailContext }) {
  const { toast } = useToast();
  const { version } = ctx;
  const [days, setDays] = useState<DayDraft[]>([]);
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [products, setProducts] = useState<ServiceProductView[] | null>(null);
  const [vehicles, setVehicles] = useState<VehicleTypeView[]>([]);
  const [pickerDay, setPickerDay] = useState<number | null>(null);
  const [customLabel, setCustomLabel] = useState("");
  const [pickerQuery, setPickerQuery] = useState("");
  // Vehicle-priced product clicked in the picker, awaiting a vehicle choice.
  const [pendingVehicleProduct, setPendingVehicleProduct] = useState<ServiceProductView | null>(null);
  const [pickerVehicle, setPickerVehicle] = useState("");
  // Auto-generation runs once per version id — the ref guards against React
  // StrictMode double-invoking the effect before the save lands.
  const autoGeneratedFor = useRef<string | null>(null);
  // Cities this component auto-filled, keyed by dayOffset — the sync never
  // overwrites a value the user typed over a derived one.
  const derivedCities = useRef<Record<number, string>>({});

  const hasStays = version.scenarios.some((sc) => sc.stays.length > 0);

  useEffect(() => {
    const loaded: DayDraft[] = version.itineraryDays.map((d) => ({
      dayOffset: d.dayOffset,
      date: d.date,
      narrative: d.narrative ?? "",
      overnightCity: d.overnightCity ?? "",
      services: normalizeDayServices(d.services),
    }));
    // Pre-fill overnight cities from stays (blank fields only — typed values
    // are never touched). Deterministic from the stays, so not marked dirty.
    derivedCities.current = {};
    let next = loaded;
    if (version.scenarios.some((sc) => sc.stays.length > 0)) {
      const cityByDate = deriveCityByDate(ctx);
      next = loaded.map((d, i) => {
        const derived = cityByDate[d.date] ?? "";
        if (derived && d.overnightCity === "") {
          derivedCities.current[i] = derived;
          return { ...d, overnightCity: derived };
        }
        return d;
      });
    }
    setDays(next);
    setDirty(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [version.id, version.itineraryDays]);

  useEffect(() => {
    if (!ctx.canEditVersion || products !== null) return;
    axios
      .get("/api/travel/catalog/services")
      .then((res) => setProducts(res.data))
      .catch((err) => toast(apiError(err, "Failed to load service catalog"), "error"));
  }, [ctx.canEditVersion, products, toast]);

  // Vehicle names also render on read-only chips, so load them unconditionally.
  useEffect(() => {
    axios
      .get("/api/travel/catalog/vehicles")
      .then((res) => setVehicles(res.data))
      .catch(() => null);
  }, []);

  const vehicleName = (id: string | null | undefined) =>
    id ? vehicles.find((v) => v.id === id)?.name ?? null : null;

  function applyCitySync(source: DayDraft[], markDirty: boolean) {
    const cityByDate = deriveCityByDate(ctx);
    let changed = false;
    const next = source.map((d, i) => {
      const derived = cityByDate[d.date] ?? "";
      const previous = derivedCities.current[i];
      // Fill only blanks and values WE derived earlier; typed cities stay.
      if (derived && (d.overnightCity === "" || d.overnightCity === previous)) {
        if (d.overnightCity !== derived) changed = true;
        derivedCities.current[i] = derived;
        return { ...d, overnightCity: derived };
      }
      return d;
    });
    if (changed) {
      setDays(next);
      if (markDirty) setDirty(true);
    }
    return changed;
  }

  function update(idx: number, patch: Partial<DayDraft>) {
    setDays((prev) => prev.map((d, i) => (i === idx ? { ...d, ...patch } : d)));
    setDirty(true);
  }

  function rederiveDates(list: DayDraft[]): DayDraft[] {
    // Dates are derived from the request start date so offset and date never diverge.
    return list.map((d, i) => ({ ...d, dayOffset: i, date: addDays(ctx.detail.startDate, i) }));
  }

  /** Pure builder: one blank day per travel date, cities pre-filled from stays. */
  function buildGeneratedDays(): DayDraft[] {
    const count = daysBetween(ctx.detail.startDate, ctx.detail.endDate);
    const generated: DayDraft[] = Array.from({ length: count }, (_, i) => ({
      dayOffset: i,
      date: addDays(ctx.detail.startDate, i),
      narrative: "",
      overnightCity: "",
      services: [],
    }));
    derivedCities.current = {};
    if (!hasStays) return generated;
    const cityMap = deriveCityByDate(ctx);
    return generated.map((d, i) => {
      const derived = cityMap[d.date] ?? "";
      if (derived) {
        derivedCities.current[i] = derived;
        return { ...d, overnightCity: derived };
      }
      return d;
    });
  }

  function generateFromTravelDates() {
    setDays(buildGeneratedDays());
    setDirty(true);
  }

  function addDay() {
    setDays(
      rederiveDates([
        ...days,
        { dayOffset: days.length, date: addDays(ctx.detail.startDate, days.length), narrative: "", overnightCity: "", services: [] },
      ]),
    );
    setDirty(true);
  }

  function removeDay(idx: number) {
    setDays(rederiveDates(days.filter((_, i) => i !== idx)));
    setDirty(true);
  }

  function addService(idx: number, item: DayServiceItem) {
    update(idx, { services: [...days[idx].services, item] });
  }

  function removeService(dayIdx: number, svcIdx: number) {
    update(dayIdx, { services: days[dayIdx].services.filter((_, i) => i !== svcIdx) });
  }

  function addCustomService() {
    const label = customLabel.trim();
    if (pickerDay === null || !label) return;
    addService(pickerDay, { serviceProductId: null, label });
    setCustomLabel("");
    closePicker();
  }

  function closePicker() {
    setPickerDay(null);
    setPendingVehicleProduct(null);
    setPickerVehicle("");
    setPickerQuery("");
  }

  function pickProduct(p: ServiceProductView) {
    if (pickerDay === null) return;
    if (needsVehicle(p) && vehicles.length > 0) {
      // Second step: the same product in two vehicles is two distinct lines.
      setPendingVehicleProduct(p);
      setPickerVehicle((prev) => prev || vehicles[0].id);
      return;
    }
    addService(pickerDay, { serviceProductId: p.id, label: p.name });
    closePicker();
  }

  function confirmVehicleProduct() {
    if (pickerDay === null || !pendingVehicleProduct || !pickerVehicle) return;
    addService(pickerDay, {
      serviceProductId: pendingVehicleProduct.id,
      label: pendingVehicleProduct.name,
      vehicleTypeId: pickerVehicle,
    });
    closePicker();
  }

  /** Persists an explicit day list — callers pass the list so an auto-save right after generation never depends on setState timing. */
  async function saveDays(list: DayDraft[], successMessage: string) {
    setSaving(true);
    try {
      await axios.put(`/api/travel/versions/${version.id}/content`, {
        expectedRevision: ctx.detail.revision,
        itineraryDays: list.map((d) => ({
          dayOffset: d.dayOffset,
          date: d.date,
          narrative: d.narrative || null,
          overnightCity: d.overnightCity || null,
          services: d.services.map((s) => ({
            serviceProductId: s.serviceProductId,
            label: s.label,
            vehicleTypeId: s.vehicleTypeId ?? null,
          })),
        })),
      });
      toast(successMessage, "success");
      setDirty(false);
      ctx.refresh();
    } catch (err: any) {
      if (err?.response?.status === 409) {
        toast("This request was edited elsewhere — refreshed the latest data. Review and save again.", "error");
        ctx.refresh();
      } else {
        toast(apiError(err, "Failed to save itinerary"), "error");
      }
    } finally {
      setSaving(false);
    }
  }

  function handleSave() {
    return saveDays(days, "Itinerary saved");
  }

  // A fresh version starts with no days: generate them from the travel dates
  // and save immediately, so the advisor lands on a ready day grid instead of
  // an empty placeholder. Editable versions only; once per version id.
  useEffect(() => {
    if (!ctx.canEditVersion) return;
    if (version.itineraryDays.length > 0) return;
    if (autoGeneratedFor.current === version.id) return;
    autoGeneratedFor.current = version.id;
    const generated = buildGeneratedDays();
    setDays(generated);
    void saveDays(generated, `Generated ${generated.length} days from travel dates`);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ctx.canEditVersion, version.id, version.itineraryDays.length]);

  const cityByDate = hasStays ? deriveCityByDate(ctx) : {};

  // Picker sections: tours split by pricing model first, then friendly labels
  // in catalog order; anything unmatched lands in "Other" so a new category
  // never silently disappears from the picker.
  const pickerQueryLower = pickerQuery.trim().toLowerCase();
  const catalog = (products ?? []).filter(
    (p) => !pickerQueryLower || p.name.toLowerCase().includes(pickerQueryLower),
  );
  const sectionDefs: { title: string; match: (p: ServiceProductView) => boolean }[] = [
    { title: "Tours — private vehicle", match: (p) => p.category === "TRANSPORTATION" && needsVehicle(p) },
    { title: "Group tours — per seat", match: (p) => p.category === "TRANSPORTATION" && !needsVehicle(p) },
    { title: "Tickets & degustations", match: (p) => p.category === "TICKETS" },
    { title: "Meals", match: (p) => p.category === "GUEST_MEALS" },
    { title: "Guides", match: (p) => p.category === "GUIDES" },
    { title: "Staff costs", match: (p) => p.category === "STAFF_ACCOMMODATION" || p.category === "STAFF_MEALS" },
    { title: "Tour leader", match: (p) => p.category === "TOUR_LEADER" },
    { title: "Extra services", match: (p) => p.category === "EXTRA_SERVICES" },
  ];
  const assigned = new Set<string>();
  const pickerSections = sectionDefs.map((def) => {
    const items = catalog.filter(def.match);
    for (const p of items) assigned.add(p.id);
    return { title: def.title, items };
  });
  pickerSections.push({ title: "Other", items: catalog.filter((p) => !assigned.has(p.id)) });
  const visibleSections = pickerSections.filter((s) => s.items.length > 0);

  const pickerList = (
    <>
      {products === null && <p className="text-sm text-muted-foreground">Loading catalog…</p>}
      {products !== null && products.length === 0 && (
        <p className="text-sm text-muted-foreground">No active services in the catalog.</p>
      )}
      {pendingVehicleProduct && (
        <div className="flex items-end gap-2 rounded-md border bg-muted/30 p-2">
          <div className="flex-1">
            <p className="mb-1 text-xs font-medium">
              {pendingVehicleProduct.name} — vehicle
            </p>
            <Select value={pickerVehicle} onValueChange={setPickerVehicle}>
              <SelectTrigger>
                <SelectValue placeholder="Select vehicle" />
              </SelectTrigger>
              <SelectContent>
                {vehicles.map((v) => (
                  <SelectItem key={v.id} value={v.id}>
                    {v.name} ({v.seats} seats)
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <Button size="sm" onClick={confirmVehicleProduct} disabled={!pickerVehicle}>
            Add
          </Button>
          <Button size="sm" variant="ghost" onClick={() => setPendingVehicleProduct(null)}>
            Back
          </Button>
        </div>
      )}
      <Input
        placeholder="Search services…"
        value={pickerQuery}
        onChange={(e) => setPickerQuery(e.target.value)}
      />
      <div className="max-h-72 space-y-3 overflow-y-auto">
        {products !== null && visibleSections.length === 0 && (
          <p className="text-sm text-muted-foreground">
            {pickerQueryLower ? "No services match this search." : "No active services in the catalog."}
          </p>
        )}
        {visibleSections.map((section) => (
          <div key={section.title}>
            <p className="mb-1 text-xs font-medium text-muted-foreground">{section.title}</p>
            <div className="space-y-1">
              {section.items.map((p) => (
                <button
                  key={p.id}
                  type="button"
                  className={`w-full rounded-md border px-2 py-1 text-left text-sm hover:bg-accent${
                    pendingVehicleProduct?.id === p.id ? " border-primary" : ""
                  }`}
                  onClick={() => pickProduct(p)}
                >
                  {p.name}
                  <span className="ml-2 text-xs text-muted-foreground">
                    {basisLabel(p.basis, p.capacity)}
                    {p.durationVariant ? ` · ${p.durationVariant.replace(/_/g, " ")}` : ""}
                    {needsVehicle(p) ? " · per vehicle" : ""}
                    {p.category === "TRANSPORTATION" && !needsVehicle(p) && weekdaysLabel(p.weekdays)
                      ? ` · departs ${weekdaysLabel(p.weekdays)}`
                      : ""}
                  </span>
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>
      <div className="flex gap-2 border-t pt-3">
        <Input
          placeholder="Custom label…"
          value={customLabel}
          onChange={(e) => setCustomLabel(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              e.preventDefault();
              addCustomService();
            }
          }}
        />
        <Button variant="outline" size="sm" onClick={addCustomService} disabled={!customLabel.trim()}>
          Add custom
        </Button>
      </div>
    </>
  );

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Itinerary</CardTitle>
            <CardDescription>
              Day-by-day plan for this version.{ctx.canEditVersion ? "" : " Read-only for this version status."}
            </CardDescription>
          </div>
          {ctx.canEditVersion && (
            <div className="flex gap-2">
              {hasStays && (
                <Button variant="outline" size="sm" onClick={() => applyCitySync(days, true)}>
                  Sync cities from stays
                </Button>
              )}
              <Button variant="outline" size="sm" onClick={addDay}>
                Add day
              </Button>
              <Button size="sm" onClick={handleSave} disabled={!dirty || saving}>
                {saving ? "Saving..." : "Save itinerary"}
              </Button>
            </div>
          )}
        </div>
      </CardHeader>
      <CardContent>
        {days.length === 0 &&
          (ctx.canEditVersion ? (
            <div className="flex flex-col items-center gap-3 rounded-md border border-dashed p-8 text-center">
              <p className="text-sm text-muted-foreground">
                No itinerary days yet. Generate one day per travel date ({ctx.detail.startDate} →{" "}
                {ctx.detail.endDate}) or add days manually.
              </p>
              <Button onClick={generateFromTravelDates}>Generate days from travel dates</Button>
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No itinerary days yet.</p>
          ))}
        <div className="space-y-3">
          {days.map((d, i) =>
            ctx.canEditVersion ? (
              <div key={i} className="grid gap-2 rounded-md border p-3 sm:grid-cols-[80px_130px_1fr_160px_1fr_40px]">
                <div className="flex items-center text-sm font-medium">Day {d.dayOffset + 1}</div>
                <Input type="date" value={d.date} onChange={(e) => update(i, { date: e.target.value })} />
                <Textarea
                  rows={2}
                  placeholder="Narrative"
                  value={d.narrative}
                  onChange={(e) => update(i, { narrative: e.target.value })}
                />
                <div>
                  <Input
                    placeholder="Overnight city"
                    value={d.overnightCity}
                    onChange={(e) => update(i, { overnightCity: e.target.value })}
                  />
                  {hasStays && !cityByDate[d.date] && (
                    // Nights span [startDate, endDate): the departure day has no
                    // overnight by definition — hint instead of warning.
                    d.date >= ctx.detail.endDate ? (
                      <p className="mt-1 text-xs text-muted-foreground">Departure day — no overnight needed</p>
                    ) : (
                      <p className="mt-1 text-xs text-amber-600">No stay covers this date</p>
                    )
                  )}
                </div>
                <div className="flex flex-wrap content-start items-start gap-1">
                  {d.services.map((s, j) => (
                    <Badge key={j} variant="outline" className="flex items-center gap-1">
                      {s.label}
                      {vehicleName(s.vehicleTypeId) ? ` · ${vehicleName(s.vehicleTypeId)}` : ""}
                      <button
                        type="button"
                        aria-label={`Remove ${s.label}`}
                        className="text-muted-foreground hover:text-foreground"
                        onClick={() => removeService(i, j)}
                      >
                        ✕
                      </button>
                    </Badge>
                  ))}
                  <Button variant="outline" size="sm" className="h-6 px-2 text-xs" onClick={() => setPickerDay(i)}>
                    + Add service
                  </Button>
                </div>
                <Button variant="ghost" size="sm" onClick={() => removeDay(i)}>
                  ✕
                </Button>
              </div>
            ) : (
              <div key={i} className="rounded-md border p-3 text-sm">
                <div className="mb-1 flex items-center gap-3 font-medium">
                  <span>Day {d.dayOffset + 1}</span>
                  <span className="text-muted-foreground">{d.date}</span>
                  {d.overnightCity && <span className="text-muted-foreground">· {d.overnightCity}</span>}
                </div>
                {d.narrative && <p className="whitespace-pre-wrap">{d.narrative}</p>}
                {d.services.length > 0 && (
                  <div className="mt-1 flex flex-wrap gap-1">
                    {d.services.map((s, j) => (
                      <Badge key={j} variant="outline" className="text-xs font-normal text-muted-foreground">
                        {s.label}
                        {vehicleName(s.vehicleTypeId) ? ` · ${vehicleName(s.vehicleTypeId)}` : ""}
                      </Badge>
                    ))}
                  </div>
                )}
              </div>
            ),
          )}
        </div>
      </CardContent>
      <Dialog open={pickerDay !== null} onOpenChange={(open) => !open && closePicker()}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Add service{pickerDay !== null ? ` — Day ${days[pickerDay]?.dayOffset + 1}` : ""}</DialogTitle>
            <DialogDescription>
              Pick a catalog service (priced automatically from its rate on this date) or add a custom label.
            </DialogDescription>
          </DialogHeader>
          {pickerList}
        </DialogContent>
      </Dialog>
    </Card>
  );
}
